### ISSUE TITLE
mountpoints list on newest lsblk not mountpoint

### ISSUE THREAD

**Issue by UlisseMini** [karlicoss/kobuddy#15]
On archlinux with lsblk from util-linux 2.37.1 I get this json output from `lsblk -f --json`
```json
{
  "name": "sda",
  "fstype": "vfat",
  "fsver": "FAT32",
  "label": "KOBOeReader",
  "uuid": "5C94-1315",
  "fsavail": "4.5G",
  "fsuse%": "33%",
  "mountpoints": [
    "/mnt/ereader"
  ]
}

```
[The code wants](https://github.com/karlicoss/kobuddy/blob/6aeaf69a3fee1574a88b19ca28e3608b605a8827/src/kobuddy/kobo_device.py#L12) `"mountpoint": "/mnt/ereader"`. so I get a `KeyError: 'mountpoint'`.

**Comment by karlicoss** [comment]
Thanks for reporting! Should be fixed here https://github.com/karlicoss/kobuddy/commit/4a8dae92ec5f916884d8bf231c31fe1d740182ae
