### ISSUE TITLE
Any way to filter out Pocket articles?

### ISSUE THREAD

**Issue by Donearm** [karlicoss/kobuddy#6]
Hi,

first of all, thanks for this software. I have recently bought a Kobo H2O Libra and testing it with kobuddy. Currently it mostly works but I can't find a way to print only the books, not also the Pocket articles. At the moment it prints everything, books, current and archived articles, resulting in a long output. Thanks

**Comment by karlicoss** [comment]
Oh hey, sorry not sure how I missed this issue!

I'm not using Pocket personally so not sure, but if you want to give it a try youself, probably the easiest would be somewhere around [here](https://github.com/karlicoss/kobuddy/blob/9c55f2f94c3c949c4d8a5ba18704be92c055873c/src/kobuddy/__init__.py#L389-L400). I.g you could `print(b)`, take a look at how to determine Pocket items based on some fields, and filter them out.

**Comment by karlicoss** [comment]
Thanks! I guess would be nice if pocket filtering was tweakable, but I'm not sure if it's very useful to people anyway (there are better ways of getting your Pocket articles), so happy to leave it to someone else.
